import type { Part } from "./types";

// Hardcoded catalog of real McMaster-Carr-style parts.
// Part numbers follow McMaster's NNNNN[A-Z]NNN format. Prefix series are drawn
// from McMaster conventions (90591A = metric hex nuts, 92510A = threaded rods,
// 93475A = round standoffs, 94639A = coupling nuts, 4452K / 4429K = NPT pipe
// fittings, 96754A = flange nuts, 90975A = T-nuts, 90710A = jam nuts,
// 91746A = thumb screws, 90866A = wing nuts, 3014T = eye bolts).
// Specific part numbers should be verified against mcmaster.com before ordering.
const mcm = (n: string) => `https://www.mcmaster.com/${n}`;

export const CATALOG: Part[] = [
  // ---- M8 threaded rods ----
  {
    partNumber: "92510A816",
    name: "Low-Strength Steel Threaded Rod, M8 x 1.25, 100 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "steel",
    finish: "zinc plated",
    length: 100,
    diameter: 8,
    mcmasterUrl: mcm("92510A816"),
  },
  {
    partNumber: "92510A820",
    name: "Low-Strength Steel Threaded Rod, M8 x 1.25, 200 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "steel",
    finish: "zinc plated",
    length: 200,
    diameter: 8,
    mcmasterUrl: mcm("92510A820"),
  },
  {
    partNumber: "92510A824",
    name: "Low-Strength Steel Threaded Rod, M8 x 1.25, 300 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "steel",
    finish: "zinc plated",
    length: 300,
    diameter: 8,
    mcmasterUrl: mcm("92510A824"),
  },
  {
    partNumber: "92510A832",
    name: "Stainless Steel Threaded Rod, M8 x 1.25, 500 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    length: 500,
    diameter: 8,
    mcmasterUrl: mcm("92510A832"),
  },
  {
    partNumber: "92510A848",
    name: "Stainless Steel Threaded Rod, M8 x 1.25, 1000 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    length: 1000,
    diameter: 8,
    mcmasterUrl: mcm("92510A848"),
  },

  // ---- M8 hex nuts ----
  {
    partNumber: "90591A160",
    name: "Zinc-Plated Steel Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 6.5,
    diameter: 13,
    mcmasterUrl: mcm("90591A160"),
  },
  {
    partNumber: "94895A100",
    name: "18-8 Stainless Steel Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 6.5,
    diameter: 13,
    mcmasterUrl: mcm("94895A100"),
  },
  {
    partNumber: "93827A210",
    name: "Black-Oxide Steel Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "black_oxide",
    finish: "black oxide",
    height: 6.5,
    diameter: 13,
    mcmasterUrl: mcm("93827A210"),
  },
  {
    partNumber: "92671A170",
    name: "Brass Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "plain",
    height: 6.5,
    diameter: 13,
    mcmasterUrl: mcm("92671A170"),
  },

  // ---- M8 coupling nuts ----
  {
    partNumber: "94639A300",
    name: "Zinc-Plated Steel Coupling Nut, M8 x 1.25, 24 mm Long",
    category: "coupling_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 24,
    diameter: 13,
    mcmasterUrl: mcm("94639A300"),
  },
  {
    partNumber: "94639A330",
    name: "Brass Coupling Nut, M8 x 1.25, 30 mm Long",
    category: "coupling_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "plain",
    height: 30,
    diameter: 13,
    mcmasterUrl: mcm("94639A330"),
  },
  {
    partNumber: "94639A340",
    name: "18-8 Stainless Steel Coupling Nut, M8 x 1.25, 40 mm Long",
    category: "coupling_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 40,
    diameter: 13,
    mcmasterUrl: mcm("94639A340"),
  },

  // ---- M8 acorn / decorative ----
  {
    partNumber: "97803A410",
    name: "Stainless Steel Acorn Cap Nut, M8 x 1.25",
    category: "acorn_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "polished",
    height: 12,
    diameter: 13,
    mcmasterUrl: mcm("97803A410"),
  },

  // ---- M8 round standoffs ----
  {
    partNumber: "93475A140",
    name: "Aluminum Round Standoff, M8 Threaded, 10 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "aluminum",
    finish: "plain",
    height: 10,
    diameter: 12,
    mcmasterUrl: mcm("93475A140"),
  },
  {
    partNumber: "93475A155",
    name: "Aluminum Round Standoff, M8 Threaded, 25 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "aluminum",
    finish: "plain",
    height: 25,
    diameter: 12,
    mcmasterUrl: mcm("93475A155"),
  },
  {
    partNumber: "93475A180",
    name: "Stainless Steel Round Standoff, M8 Threaded, 50 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 50,
    diameter: 12,
    mcmasterUrl: mcm("93475A180"),
  },
  {
    partNumber: "93475A220",
    name: "Brass Round Standoff, M8 Threaded, 75 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "polished",
    height: 75,
    diameter: 12,
    mcmasterUrl: mcm("93475A220"),
  },
  {
    partNumber: "93475A260",
    name: "Brass Round Standoff, M8 Threaded, 100 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "polished",
    height: 100,
    diameter: 12,
    mcmasterUrl: mcm("93475A260"),
  },

  // ---- M8 knurled thumb screws (terminal — flat broad head) ----
  {
    partNumber: "91746A220",
    name: "Brass Knurled-Head Thumb Screw, M8 x 1.25, 16 mm Long",
    category: "thumb_screw",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "plain",
    height: 24, // total visual height incl. head
    diameter: 18, // head diameter
    mcmasterUrl: mcm("91746A220"),
  },
  {
    partNumber: "91746A230",
    name: "18-8 Stainless Steel Knurled-Head Thumb Screw, M8 x 1.25, 20 mm Long",
    category: "thumb_screw",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "polished",
    height: 28,
    diameter: 20,
    mcmasterUrl: mcm("91746A230"),
  },

  // ---- M8 wing nuts (terminal — butterfly silhouette) ----
  {
    partNumber: "90866A110",
    name: "Zinc-Plated Steel Wing Nut, M8 x 1.25",
    category: "wing_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 11,
    diameter: 28, // wing-tip to wing-tip
    mcmasterUrl: mcm("90866A110"),
  },
  {
    partNumber: "94895A800",
    name: "18-8 Stainless Steel Wing Nut, M8 x 1.25",
    category: "wing_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 12,
    diameter: 30,
    mcmasterUrl: mcm("94895A800"),
  },

  // ---- M8 flange nuts (wide-base) ----
  {
    partNumber: "96754A150",
    name: "Zinc-Plated Steel Serrated Flange Nut, M8 x 1.25",
    category: "flange_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 9,
    diameter: 19, // flange OD
    mcmasterUrl: mcm("96754A150"),
  },
  {
    partNumber: "96754A160",
    name: "18-8 Stainless Steel Serrated Flange Nut, M8 x 1.25",
    category: "flange_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 9,
    diameter: 19,
    mcmasterUrl: mcm("96754A160"),
  },

  // ---- M8 eye bolts (terminal — loop visual) ----
  {
    partNumber: "3014T11",
    name: "Zinc-Plated Steel Eye Bolt, M8 x 1.25, 30 mm Long",
    category: "eye_bolt",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    length: 52, // includes loop
    diameter: 18, // loop OD
    mcmasterUrl: mcm("3014T11"),
  },
  {
    partNumber: "3014T21",
    name: "18-8 Stainless Steel Eye Bolt, M8 x 1.25, 40 mm Long",
    category: "eye_bolt",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    length: 66,
    diameter: 20,
    mcmasterUrl: mcm("3014T21"),
  },

  // ---- M8 T-nuts ----
  {
    partNumber: "90975A100",
    name: "Zinc-Plated Steel T-Nut, M8 x 1.25",
    category: "t_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 11,
    diameter: 22, // flange OD
    mcmasterUrl: mcm("90975A100"),
  },
  {
    partNumber: "90975A110",
    name: "18-8 Stainless Steel T-Nut, M8 x 1.25",
    category: "t_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 11,
    diameter: 22,
    mcmasterUrl: mcm("90975A110"),
  },

  // ---- M8 jam nuts (thin) ----
  {
    partNumber: "90710A140",
    name: "Zinc-Plated Steel Jam Nut, M8 x 1.25 (Thin)",
    category: "jam_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 4,
    diameter: 13,
    mcmasterUrl: mcm("90710A140"),
  },
  {
    partNumber: "90710A150",
    name: "18-8 Stainless Steel Jam Nut, M8 x 1.25 (Thin)",
    category: "jam_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 4,
    diameter: 13,
    mcmasterUrl: mcm("90710A150"),
  },

  // ---- 1/4" NPT pipe nipples ----
  {
    partNumber: "4452K131",
    name: "Galvanized Steel Pipe Nipple, 1/4 NPT x 1/4 NPT, Close",
    category: "pipe_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    length: 28,
    diameter: 13.7,
    mcmasterUrl: mcm("4452K131"),
  },
  {
    partNumber: "4452K141",
    name: "Galvanized Steel Pipe Nipple, 1/4 NPT, 2 in Long",
    category: "pipe_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    length: 51,
    diameter: 13.7,
    mcmasterUrl: mcm("4452K141"),
  },

  // ---- 1/4" NPT barrel nipples (short, hex-bodied) ----
  {
    partNumber: "4452K151",
    name: "Galvanized Steel Barrel Nipple, 1/4 NPT, 1-1/2 in Long",
    category: "barrel_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    length: 38,
    diameter: 16,
    mcmasterUrl: mcm("4452K151"),
  },
  {
    partNumber: "4452K161",
    name: "Brass Barrel Nipple, 1/4 NPT, 1-1/2 in Long",
    category: "barrel_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    length: 38,
    diameter: 16,
    mcmasterUrl: mcm("4452K161"),
  },
  {
    partNumber: "4452K171",
    name: "Galvanized Steel Barrel Nipple, 1/4 NPT, 3 in Long",
    category: "barrel_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    length: 76,
    diameter: 16,
    mcmasterUrl: mcm("4452K171"),
  },

  // ---- 1/4" NPT couplings ----
  {
    partNumber: "4429K151",
    name: "Galvanized Steel Pipe Coupling, 1/4 NPT",
    category: "pipe_coupling",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 26,
    diameter: 19,
    mcmasterUrl: mcm("4429K151"),
  },

  // ---- 1/4" NPT tees (top, left, right ports) ----
  {
    partNumber: "4429K271",
    name: "Brass Pipe Tee, 1/4 NPT",
    category: "pipe_tee",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    height: 28,
    diameter: 28,
    mcmasterUrl: mcm("4429K271"),
  },
  {
    partNumber: "4429K281",
    name: "Galvanized Steel Pipe Tee, 1/4 NPT",
    category: "pipe_tee",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 28,
    diameter: 28,
    mcmasterUrl: mcm("4429K281"),
  },
  {
    partNumber: "4429K291",
    name: "304 Stainless Steel Pipe Tee, 1/4 NPT",
    category: "pipe_tee",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "stainless",
    finish: "passivated",
    height: 28,
    diameter: 28,
    mcmasterUrl: mcm("4429K291"),
  },

  // ---- 1/4" NPT 90° elbows ----
  {
    partNumber: "4429K321",
    name: "Brass 90° Elbow, 1/4 NPT",
    category: "pipe_elbow",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    height: 24,
    diameter: 24,
    mcmasterUrl: mcm("4429K321"),
  },
  {
    partNumber: "4429K331",
    name: "Galvanized Steel 90° Elbow, 1/4 NPT",
    category: "pipe_elbow",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 24,
    diameter: 24,
    mcmasterUrl: mcm("4429K331"),
  },
  {
    partNumber: "4429K341",
    name: "304 Stainless Steel 90° Elbow, 1/4 NPT",
    category: "pipe_elbow",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "stainless",
    finish: "passivated",
    height: 24,
    diameter: 24,
    mcmasterUrl: mcm("4429K341"),
  },

  // ---- 1/4" NPT crosses (4-way, rare) ----
  {
    partNumber: "4429K411",
    name: "Galvanized Steel 4-Way Cross, 1/4 NPT",
    category: "pipe_cross",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 30,
    diameter: 30,
    mcmasterUrl: mcm("4429K411"),
  },
  {
    partNumber: "4429K421",
    name: "Brass 4-Way Cross, 1/4 NPT",
    category: "pipe_cross",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    height: 30,
    diameter: 30,
    mcmasterUrl: mcm("4429K421"),
  },

  // ---- 1/4" NPT pipe caps (terminal) ----
  {
    partNumber: "4452K811",
    name: "Brass Pipe Cap, 1/4 NPT",
    category: "pipe_cap",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    height: 18,
    diameter: 20,
    mcmasterUrl: mcm("4452K811"),
  },
  {
    partNumber: "4452K821",
    name: "Galvanized Steel Pipe Cap, 1/4 NPT",
    category: "pipe_cap",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 18,
    diameter: 20,
    mcmasterUrl: mcm("4452K821"),
  },

  // ---- 1/4" NPT pipe plugs (terminal — hex/square head insert) ----
  {
    partNumber: "4452K711",
    name: "Brass Hex-Head Pipe Plug, 1/4 NPT",
    category: "pipe_plug",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    height: 14,
    diameter: 17,
    mcmasterUrl: mcm("4452K711"),
  },
  {
    partNumber: "4452K721",
    name: "Galvanized Steel Square-Head Pipe Plug, 1/4 NPT",
    category: "pipe_plug",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 14,
    diameter: 17,
    mcmasterUrl: mcm("4452K721"),
  },
];

export function partsByCategory(
  threadType: Part["threadType"],
  category: Part["category"],
): Part[] {
  return CATALOG.filter(
    (p) => p.threadType === threadType && p.category === category,
  );
}

export function partsForThread(threadType: Part["threadType"]): Part[] {
  return CATALOG.filter((p) => p.threadType === threadType);
}
