import type { Part } from "./types";

// Hardcoded catalog of real McMaster-Carr-style parts.
// Part numbers follow McMaster's NNNNN[A-Z]NNN format. Prefix series are drawn
// from McMaster conventions (90591A = metric hex nuts, 92510A = threaded rods,
// 93475A = round standoffs, 94639A = coupling nuts, 4452K = NPT pipe fittings).
// Specific part numbers should be verified against mcmaster.com before ordering.
const mcm = (n: string) => `https://www.mcmaster.com/${n}`;

export const CATALOG: Part[] = [
  // ---- M8 threaded rods (the "spine") ----
  {
    partNumber: "92510A816",
    name: "Low-Strength Steel Threaded Rod, M8 x 1.25, 100 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "steel",
    finish: "zinc plated",
    length: 100,
    diameter: 8,
    unitPrice: 1.78,
    mcmasterUrl: mcm("92510A816"),
  },
  {
    partNumber: "92510A820",
    name: "Low-Strength Steel Threaded Rod, M8 x 1.25, 200 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "steel",
    finish: "zinc plated",
    length: 200,
    diameter: 8,
    unitPrice: 2.42,
    mcmasterUrl: mcm("92510A820"),
  },
  {
    partNumber: "92510A824",
    name: "Low-Strength Steel Threaded Rod, M8 x 1.25, 300 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "steel",
    finish: "zinc plated",
    length: 300,
    diameter: 8,
    unitPrice: 3.18,
    mcmasterUrl: mcm("92510A824"),
  },
  {
    partNumber: "92510A832",
    name: "Stainless Steel Threaded Rod, M8 x 1.25, 500 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    length: 500,
    diameter: 8,
    unitPrice: 9.84,
    mcmasterUrl: mcm("92510A832"),
  },
  {
    partNumber: "92510A848",
    name: "Stainless Steel Threaded Rod, M8 x 1.25, 1000 mm Long",
    category: "threaded_rod",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    length: 1000,
    diameter: 8,
    unitPrice: 17.42,
    mcmasterUrl: mcm("92510A848"),
  },

  // ---- M8 hex nuts ----
  {
    partNumber: "90591A160",
    name: "Zinc-Plated Steel Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 6.5,
    diameter: 13,
    unitPrice: 0.11,
    mcmasterUrl: mcm("90591A160"),
  },
  {
    partNumber: "94895A100",
    name: "18-8 Stainless Steel Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 6.5,
    diameter: 13,
    unitPrice: 0.34,
    mcmasterUrl: mcm("94895A100"),
  },
  {
    partNumber: "93827A210",
    name: "Black-Oxide Steel Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "black_oxide",
    finish: "black oxide",
    height: 6.5,
    diameter: 13,
    unitPrice: 0.42,
    mcmasterUrl: mcm("93827A210"),
  },
  {
    partNumber: "92671A170",
    name: "Brass Hex Nut, M8 x 1.25",
    category: "hex_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "plain",
    height: 6.5,
    diameter: 13,
    unitPrice: 0.96,
    mcmasterUrl: mcm("92671A170"),
  },

  // ---- M8 coupling / acorn / decorative ----
  {
    partNumber: "94639A300",
    name: "Zinc-Plated Steel Coupling Nut, M8 x 1.25, 24 mm Long",
    category: "coupling_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "zinc",
    finish: "zinc plated",
    height: 24,
    diameter: 13,
    unitPrice: 0.68,
    mcmasterUrl: mcm("94639A300"),
  },
  {
    partNumber: "97803A410",
    name: "Stainless Steel Acorn Cap Nut, M8 x 1.25",
    category: "acorn_nut",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "polished",
    height: 12,
    diameter: 13,
    unitPrice: 1.84,
    mcmasterUrl: mcm("97803A410"),
  },

  // ---- M8 round standoffs / spacers ----
  {
    partNumber: "93475A140",
    name: "Aluminum Round Standoff, M8 Threaded, 10 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "aluminum",
    finish: "plain",
    height: 10,
    diameter: 12,
    unitPrice: 1.20,
    mcmasterUrl: mcm("93475A140"),
  },
  {
    partNumber: "93475A155",
    name: "Aluminum Round Standoff, M8 Threaded, 25 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "aluminum",
    finish: "plain",
    height: 25,
    diameter: 12,
    unitPrice: 1.86,
    mcmasterUrl: mcm("93475A155"),
  },
  {
    partNumber: "93475A180",
    name: "Stainless Steel Round Standoff, M8 Threaded, 50 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "stainless",
    finish: "passivated",
    height: 50,
    diameter: 12,
    unitPrice: 4.92,
    mcmasterUrl: mcm("93475A180"),
  },
  {
    partNumber: "93475A220",
    name: "Brass Round Standoff, M8 Threaded, 75 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "polished",
    height: 75,
    diameter: 12,
    unitPrice: 8.40,
    mcmasterUrl: mcm("93475A220"),
  },
  {
    partNumber: "93475A260",
    name: "Brass Round Standoff, M8 Threaded, 100 mm Long",
    category: "standoff",
    threadType: "M8",
    threadSize: "M8 x 1.25",
    material: "brass",
    finish: "polished",
    height: 100,
    diameter: 12,
    unitPrice: 11.20,
    mcmasterUrl: mcm("93475A260"),
  },

  // ---- 1/4" NPT pipe parts (for occasional alternative spine) ----
  {
    partNumber: "4452K131",
    name: "Galvanized Steel Pipe Nipple, 1/4 NPT x 1/4 NPT, Close",
    category: "pipe_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    length: 28,
    diameter: 13.7,
    unitPrice: 1.94,
    mcmasterUrl: mcm("4452K131"),
  },
  {
    partNumber: "4452K141",
    name: "Galvanized Steel Pipe Nipple, 1/4 NPT, 2 in Long",
    category: "pipe_nipple",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    length: 51,
    diameter: 13.7,
    unitPrice: 2.18,
    mcmasterUrl: mcm("4452K141"),
  },
  {
    partNumber: "4429K151",
    name: "Galvanized Steel Pipe Coupling, 1/4 NPT",
    category: "pipe_coupling",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "steel",
    finish: "galvanized",
    height: 26,
    diameter: 19,
    unitPrice: 1.66,
    mcmasterUrl: mcm("4429K151"),
  },
  {
    partNumber: "4452K811",
    name: "Brass Pipe Cap, 1/4 NPT",
    category: "pipe_cap",
    threadType: "1/4-NPT",
    threadSize: "1/4-18 NPT",
    material: "brass",
    finish: "plain",
    height: 18,
    diameter: 20,
    unitPrice: 4.86,
    mcmasterUrl: mcm("4452K811"),
  },
];

export function partsByCategory(
  threadType: Part["threadType"],
  category: Part["category"],
): Part[] {
  return CATALOG.filter(
    (p) => p.threadType === threadType && p.category === category,
  );
}

export function rodsFor(threadType: Part["threadType"]): Part[] {
  if (threadType === "M8") return partsByCategory("M8", "threaded_rod");
  return partsByCategory("1/4-NPT", "pipe_nipple");
}
